const express=require('express');const cors=require('cors');const bcrypt=require('bcryptjs');const Database=require('better-sqlite3');const crypto=require('crypto');const path=require('path');
const app=express();const PORT=process.env.PORT||10000;const FRONTEND_URL=(process.env.FRONTEND_URL||'https://masudjr-official-online.netlify.app').replace(/\/$/,'');
app.use(cors({origin:(origin,cb)=>{if(!origin||origin===FRONTEND_URL||origin.endsWith('.netlify.app')) return cb(null,true);cb(null,false);},credentials:false}));app.use(express.json({limit:'100kb'}));
const db=new Database(path.join(__dirname,'masud-jr.db'));db.pragma('journal_mode=WAL');
function q(sql){return db.prepare(sql)}
q(`CREATE TABLE IF NOT EXISTS admins(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TEXT NOT NULL)`).run();
q(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,balance INTEGER NOT NULL DEFAULT 0,blocked INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL)`).run();
q(`CREATE TABLE IF NOT EXISTS user_sessions(session TEXT PRIMARY KEY,user_id INTEGER NOT NULL,created_at TEXT NOT NULL,expires_at TEXT NOT NULL)`).run();
q(`CREATE TABLE IF NOT EXISTS admin_sessions(session TEXT PRIMARY KEY,admin_id INTEGER NOT NULL,created_at TEXT NOT NULL,expires_at TEXT NOT NULL)`).run();
q(`CREATE TABLE IF NOT EXISTS tasks(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,type TEXT NOT NULL,description TEXT,url TEXT,reward INTEGER NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL)`).run();
q(`CREATE TABLE IF NOT EXISTS task_attempts(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,task_id INTEGER NOT NULL,started_at TEXT NOT NULL,last_heartbeat TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'started')`).run();
q(`CREATE TABLE IF NOT EXISTS task_completions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,task_id INTEGER NOT NULL,reward INTEGER NOT NULL,completed_at TEXT NOT NULL)`).run();
q(`CREATE TABLE IF NOT EXISTS history(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,title TEXT NOT NULL,amount INTEGER NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL)`).run();
q(`CREATE TABLE IF NOT EXISTS notices(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,message TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL)`).run();
q(`CREATE TABLE IF NOT EXISTS fee_payments(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,amount INTEGER NOT NULL DEFAULT 70,transaction_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL,reviewed_at TEXT)`).run();
q(`CREATE TABLE IF NOT EXISTS withdrawals(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,method TEXT NOT NULL,account_number TEXT NOT NULL,amount INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'processing',created_at TEXT NOT NULL,reviewed_at TEXT)`).run();

const now=()=>new Date().toISOString(), token=()=>crypto.randomBytes(32).toString('hex');
function userFromReq(req){const s=req.header('x-user-session');if(!s)return null;return q(`SELECT u.* FROM user_sessions s JOIN users u ON u.id=s.user_id WHERE s.session=? AND s.expires_at>?`).get(s,now())||null;}
function adminFromReq(req){const s=req.header('x-admin-session');if(!s)return null;return q(`SELECT a.* FROM admin_sessions s JOIN admins a ON a.id=s.admin_id WHERE s.session=? AND s.expires_at>?`).get(s,now())||null;}
function ensureAdmin(){const user=process.env.ADMIN_USERNAME||'admin';let pwd=process.env.ADMIN_PASSWORD;if(!pwd){if(process.env.NODE_ENV==='production') throw new Error('ADMIN_PASSWORD is required in production');pwd='Admin@12345';}const existing=q(`SELECT id FROM admins WHERE username=?`).get(user);if(!existing)q(`INSERT INTO admins(username,password_hash,created_at) VALUES(?,?,?)`).run(user,bcrypt.hashSync(pwd,12),now());}
ensureAdmin();
const defaultTasks=[['Facebook Like','Facebook','Facebook Like task','https://www.facebook.com/',10],['Facebook Follow','Facebook','Facebook Follow task','https://www.facebook.com/',10],['TikTok Video 1','TikTok','ভিডিও দেখুন ১০ সেকেন্ড','https://www.tiktok.com/',50],['TikTok Video 2','TikTok','ভিডিও দেখুন ১০ সেকেন্ড','https://www.tiktok.com/',50],['TikTok Video 3','TikTok','ভিডিও দেখুন ১০ সেকেন্ড','https://www.tiktok.com/',50],['TikTok Video 4','TikTok','ভিডিও দেখুন ১০ সেকেন্ড','https://www.tiktok.com/',50],['TikTok Video 5','TikTok','ভিডিও দেখুন ১০ সেকেন্ড','https://www.tiktok.com/',50],['TikTok Video 6','TikTok','ভিডিও দেখুন ১০ সেকেন্ড','https://www.tiktok.com/',50],['TikTok Video 7','TikTok','ভিডিও দেখুন ১০ সেকেন্ড','https://www.tiktok.com/',50],['App Install','App','App install task','https://play.google.com/',20],['Website Visit','Website','Website visit task','https://www.google.com/',5]];
if(q('SELECT COUNT(*) c FROM tasks').get().c===0){const ins=q('INSERT INTO tasks(title,type,description,url,reward,created_at) VALUES(?,?,?,?,?,?)');for(const t of defaultTasks)ins.run(...t,now());}
if(q('SELECT COUNT(*) c FROM notices').get().c===0)q('INSERT INTO notices(title,message,created_at) VALUES(?,?,?)').run('স্বাগতম','Masud JR Official-এ স্বাগতম। নতুন task ও গুরুত্বপূর্ণ ঘোষণা এখানে পাবেন।',now());

app.get('/api/health',(req,res)=>res.json({ok:true,service:'Masud JR Official API',time:now()}));
app.post('/api/register',(req,res)=>{const name=String(req.body.name||'').trim(),password=String(req.body.password||'');if(name.length<2||password.length<6)return res.status(400).json({message:'নাম এবং কমপক্ষে 6 অক্ষরের password দিন।'});if(q('SELECT id FROM users WHERE lower(name)=lower(?)').get(name))return res.status(409).json({message:'এই নাম দিয়ে account আগে থেকেই আছে।'});const info=q('INSERT INTO users(name,password_hash,created_at) VALUES(?,?,?)').run(name,bcrypt.hashSync(password,12),now());const s=token(),exp=new Date(Date.now()+30*864e5).toISOString();q('INSERT INTO user_sessions(session,user_id,created_at,expires_at) VALUES(?,?,?,?)').run(s,info.lastInsertRowid,now(),exp);const u=q('SELECT id,name,balance,blocked,created_at FROM users WHERE id=?').get(info.lastInsertRowid);res.json({session:s,user:u});});
app.post('/api/login',(req,res)=>{const name=String(req.body.name||'').trim(),password=String(req.body.password||'');const u=q('SELECT * FROM users WHERE lower(name)=lower(?)').get(name);if(!u||!bcrypt.compareSync(password,u.password_hash))return res.status(401).json({message:'Name অথবা password ভুল।'});if(u.blocked)return res.status(403).json({message:'আপনার account blocked।'});const s=token(),exp=new Date(Date.now()+30*864e5).toISOString();q('INSERT INTO user_sessions(session,user_id,created_at,expires_at) VALUES(?,?,?,?)').run(s,u.id,now(),exp);res.json({session:s,user:{id:u.id,name:u.name,balance:u.balance,blocked:u.blocked,created_at:u.created_at}});});
app.post('/api/logout',(req,res)=>{const s=req.header('x-user-session');if(s)q('DELETE FROM user_sessions WHERE session=?').run(s);res.json({ok:true});});
app.get('/api/me',(req,res)=>{const u=userFromReq(req);if(!u)return res.status(401).json({message:'Session expired'});res.json({user:{id:u.id,name:u.name,balance:u.balance,blocked:u.blocked,created_at:u.created_at}});});
app.get('/api/dashboard',(req,res)=>{const u=userFromReq(req);if(!u)return res.status(401).json({message:'Session expired'});const start=new Date();start.setHours(0,0,0,0);const today=start.toISOString();const todayEarnings=q('SELECT COALESCE(SUM(amount),0) s FROM history WHERE user_id=? AND status="Completed" AND created_at>=?').get(u.id,today).s;const totalE=q('SELECT COALESCE(SUM(amount),0) s FROM history WHERE user_id=? AND status="Completed" AND amount>0').get(u.id).s;const completed=q('SELECT COUNT(*) c FROM task_completions WHERE user_id=?').get(u.id).c;res.json({balance:u.balance,todayEarnings:todayEarnings,totalEarnings:totalE,completedCount:completed});});
app.get('/api/tasks',(req,res)=>{const u=userFromReq(req);if(!u)return res.status(401).json({message:'Session expired'});const rows=q(`SELECT t.*,MAX(c.completed_at) last_completed FROM tasks t LEFT JOIN task_completions c ON c.task_id=t.id AND c.user_id=? WHERE t.enabled=1 GROUP BY t.id ORDER BY t.id`).all(u.id);const tasks=rows.map(r=>{let available_at=null;if(r.last_completed)available_at=new Date(new Date(r.last_completed).getTime()+5*3600e3).toISOString();return {...r,available_at:(available_at&&new Date(available_at)>new Date())?available_at:null};});res.json({tasks});});
function latestCompletion(u,t){return q('SELECT completed_at FROM task_completions WHERE user_id=? AND task_id=? ORDER BY id DESC LIMIT 1').get(u.id,t.id);}
app.post('/api/tasks/:id/start',(req,res)=>{const u=userFromReq(req);if(!u)return res.status(401).json({message:'Session expired'});const t=q('SELECT * FROM tasks WHERE id=? AND enabled=1').get(req.params.id);if(!t)return res.status(404).json({message:'Task পাওয়া যায়নি'});const last=latestCompletion(u,t);if(last&&Date.now()-Date.parse(last.completed_at)<5*3600e3)return res.status(409).json({message:'এই Task আবার করার জন্য 5 ঘণ্টা অপেক্ষা করুন।'});q(`UPDATE task_attempts SET status='cancelled' WHERE user_id=? AND task_id=? AND status='started'`).run(u.id,t.id);q('INSERT INTO task_attempts(user_id,task_id,started_at,last_heartbeat,status) VALUES(?,?,?,?,?)').run(u.id,t.id,now(),now(),'started');res.json({ok:true,taskId:t.id});});
app.post('/api/tasks/:id/heartbeat',(req,res)=>{const u=userFromReq(req);if(!u)return res.status(401).json({message:'Session expired'});q(`UPDATE task_attempts SET last_heartbeat=? WHERE id=(SELECT id FROM task_attempts WHERE user_id=? AND task_id=? AND status='started' ORDER BY id DESC LIMIT 1)`).run(now(),u.id,req.params.id);res.json({ok:true});});
app.post('/api/tasks/:id/cancel',(req,res)=>{const u=userFromReq(req);if(!u)return res.status(401).json({message:'Session expired'});q(`UPDATE task_attempts SET status='cancelled' WHERE user_id=? AND task_id=? AND status='started'`).run(u.id,req.params.id);res.json({ok:true});});
app.post('/api/tasks/:id/complete',(req,res)=>{const u=userFromReq(req);if(!u)return res.status(401).json({message:'Session expired'});const tx=db.transaction(()=>{const t=q('SELECT * FROM tasks WHERE id=? AND enabled=1').get(req.params.id);if(!t)throw new Error('Task পাওয়া যায়নি');const attempt=q(`SELECT * FROM task_attempts WHERE user_id=? AND task_id=? AND status='started' ORDER BY id DESC LIMIT 1`).get(u.id,t.id);if(!attempt)throw new Error('Active Task session পাওয়া যায়নি।');if(Date.now()-Date.parse(attempt.started_at)<10000)throw new Error('10 সেকেন্ড পূর্ণ হয়নি।');if(Date.now()-Date.parse(attempt.last_heartbeat)>8000)throw new Error('Task session বন্ধ হয়ে গেছে। আবার Start Task করুন।');const last=latestCompletion(u,t);if(last&&Date.now()-Date.parse(last.completed_at)<5*3600e3)throw new Error('এই Task আবার করার জন্য 5 ঘণ্টা অপেক্ষা করুন।');q(`UPDATE task_attempts SET status='completed' WHERE id=?`).run(attempt.id);q('INSERT INTO task_completions(user_id,task_id,reward,completed_at) VALUES(?,?,?,?)').run(u.id,t.id,t.reward,now());q('UPDATE users SET balance=balance+? WHERE id=?').run(t.reward,u.id);q('INSERT INTO history(user_id,title,amount,status,created_at) VALUES(?,?,?,?,?)').run(u.id,t.title,t.reward,'Completed',now());return t.reward;});try{const reward=tx();res.json({ok:true,reward});}catch(e){res.status(400).json({message:e.message});}});
app.get('/api/history',(req,res)=>{const u=userFromReq(req);if(!u)return res.status(401).json({message:'Session expired'});res.json({history:q('SELECT title,amount,status,created_at FROM history WHERE user_id=? ORDER BY id DESC LIMIT 100').all(u.id)});});
app.get('/api/notices',(req,res)=>{if(!userFromReq(req))return res.status(401).json({message:'Session expired'});res.json({notices:q('SELECT id,title,message,created_at FROM notices WHERE enabled=1 ORDER BY id DESC').all()});});
app.get('/api/fee-status',(req,res)=>{const u=userFromReq(req);if(!u)return res.status(401).json({message:'Session expired'});const first=q('SELECT id FROM withdrawals WHERE user_id=? LIMIT 1').get(u.id);if(first)return res.json({required:false,status:'not_required'});const f=q('SELECT status FROM fee_payments WHERE user_id=? ORDER BY id DESC LIMIT 1').get(u.id);res.json({required:!f||f.status!=='approved',status:f?.status||'required'});});
app.post('/api/fee-payments',(req,res)=>{const u=userFromReq(req);if(!u)return res.status(401).json({message:'Session expired'});const tx=String(req.body.transactionId||'').trim();if(tx.length<4)return res.status(400).json({message:'Transaction ID দিন।'});q('INSERT INTO fee_payments(user_id,transaction_id,status,created_at) VALUES(?,?,?,?)').run(u.id,tx,'pending',now());res.json({ok:true,status:'pending'});});
app.post('/api/withdrawals',(req,res)=>{const u=userFromReq(req);if(!u)return res.status(401).json({message:'Session expired'});const method=String(req.body.method||''),num=String(req.body.accountNumber||'').trim(),amount=Number(req.body.amount);if(!['bKash','Nagad','Rocket'].includes(method))return res.status(400).json({message:'Payment method ভুল।'});if(!/^01\d{9}$/.test(num))return res.status(400).json({message:'সঠিক ১১ সংখ্যার account number দিন।'});if(!Number.isInteger(amount)||amount<200)return res.status(400).json({message:'Minimum withdrawal ৳200।'});if(amount>u.balance)return res.status(400).json({message:'Balance কম।'});const first=!q('SELECT id FROM withdrawals WHERE user_id=? LIMIT 1').get(u.id);if(first){const fee=q('SELECT status FROM fee_payments WHERE user_id=? ORDER BY id DESC LIMIT 1').get(u.id);if(!fee||fee.status!=='approved')return res.status(403).json({message:'প্রথম withdrawal-এর Processing Fee আগে Admin দ্বারা approve হতে হবে।'});}const tx=db.transaction(()=>{q('UPDATE users SET balance=balance-? WHERE id=?').run(amount,u.id);const id=q('INSERT INTO withdrawals(user_id,method,account_number,amount,status,created_at) VALUES(?,?,?,?,?,?)').run(u.id,method,num,amount,'processing',now()).lastInsertRowid;q('INSERT INTO history(user_id,title,amount,status,created_at) VALUES(?,?,?,?,?)').run(u.id,`Withdrawal (${method})`,-amount,'Processing',now());return id;});res.json({ok:true,id:tx});});

app.post('/api/admin/login',(req,res)=>{const a=q('SELECT * FROM admins WHERE username=?').get(String(req.body.username||''));if(!a||!bcrypt.compareSync(String(req.body.password||''),a.password_hash))return res.status(401).json({message:'Admin login ভুল।'});const s=token(),exp=new Date(Date.now()+24*3600e3).toISOString();q('INSERT INTO admin_sessions(session,admin_id,created_at,expires_at) VALUES(?,?,?,?)').run(s,a.id,now(),exp);res.json({session:s});});
app.post('/api/admin/logout',(req,res)=>{const s=req.header('x-admin-session');if(s)q('DELETE FROM admin_sessions WHERE session=?').run(s);res.json({ok:true});});
function adminOnly(req,res,next){if(!adminFromReq(req))return res.status(401).json({message:'Admin session expired'});next();}
app.get('/api/admin/dashboard',adminOnly,(req,res)=>{const users=q('SELECT COUNT(*) c FROM users').get().c,active=q('SELECT COUNT(*) c FROM users WHERE blocked=0').get().c,pending=q("SELECT COUNT(*) c FROM withdrawals WHERE status IN ('processing','pending')").get().c,paid=q("SELECT COALESCE(SUM(amount),0) s FROM withdrawals WHERE status='paid'").get().s;res.json({users,active,pending,paid});});
app.get('/api/admin/users',adminOnly,(req,res)=>res.json({users:q('SELECT id,name,balance,blocked,created_at FROM users ORDER BY id DESC').all()}));
app.post('/api/admin/users/:id/block',adminOnly,(req,res)=>{q('UPDATE users SET blocked=? WHERE id=?').run(req.body.blocked?1:0,req.params.id);res.json({ok:true});});
app.post('/api/admin/users/:id/balance',adminOnly,(req,res)=>{const delta=Number(req.body.delta);if(!Number.isInteger(delta))return res.status(400).json({message:'Invalid amount'});const u=q('SELECT name FROM users WHERE id=?').get(req.params.id);if(!u)return res.status(404).json({message:'User not found'});q('UPDATE users SET balance=balance+? WHERE id=?').run(delta,req.params.id);q('INSERT INTO history(user_id,title,amount,status,created_at) VALUES(?,?,?,?,?)').run(req.params.id,'Admin balance adjustment',delta>=0?delta:delta,'Completed',now());res.json({ok:true});});
app.get('/api/admin/tasks',adminOnly,(req,res)=>res.json({tasks:q('SELECT * FROM tasks ORDER BY id DESC').all()}));
app.post('/api/admin/tasks',adminOnly,(req,res)=>{const {title,type,description,url,reward,enabled=true}=req.body;if(!title||!Number.isInteger(Number(reward)))return res.status(400).json({message:'Title ও reward দিন'});const id=q('INSERT INTO tasks(title,type,description,url,reward,enabled,created_at) VALUES(?,?,?,?,?,?,?)').run(title,type||'Task',description||'',url||'',Number(reward),enabled?1:0,now()).lastInsertRowid;res.json({ok:true,id});});
app.post('/api/admin/tasks/:id/toggle',adminOnly,(req,res)=>{q('UPDATE tasks SET enabled=? WHERE id=?').run(req.body.enabled?1:0,req.params.id);res.json({ok:true});});
app.post('/api/admin/tasks/:id/update',adminOnly,(req,res)=>{const {title,type,description,url,reward}=req.body;q('UPDATE tasks SET title=?,type=?,description=?,url=?,reward=? WHERE id=?').run(title,type,description,url,Number(reward),req.params.id);res.json({ok:true});});
app.get('/api/admin/withdrawals',adminOnly,(req,res)=>res.json({withdrawals:q(`SELECT w.*,u.name FROM withdrawals w JOIN users u ON u.id=w.user_id ORDER BY w.id DESC`).all()}));
app.post('/api/admin/withdrawals/:id/status',adminOnly,(req,res)=>{const status=String(req.body.status||'');if(!['processing','approved','paid','rejected'].includes(status))return res.status(400).json({message:'Invalid status'});const w=q('SELECT * FROM withdrawals WHERE id=?').get(req.params.id);if(!w)return res.status(404).json({message:'Not found'});if(w.status!==status){if(status==='rejected'&&w.status!=='rejected')q('UPDATE users SET balance=balance+? WHERE id=?').run(w.amount,w.user_id);if(status==='rejected')q('UPDATE history SET status="Rejected" WHERE user_id=? AND title=? AND amount=? AND status="Processing"').run(w.user_id,`Withdrawal (${w.method})`,-w.amount);if(status==='paid')q('UPDATE history SET status="Paid" WHERE user_id=? AND title=? AND amount=? AND status IN ("Processing","Completed")').run(w.user_id,`Withdrawal (${w.method})`,-w.amount);}q('UPDATE withdrawals SET status=?,reviewed_at=? WHERE id=?').run(status,now(),req.params.id);res.json({ok:true});});
app.get('/api/admin/fees',adminOnly,(req,res)=>res.json({fees:q(`SELECT f.*,u.name FROM fee_payments f JOIN users u ON u.id=f.user_id ORDER BY f.id DESC`).all()}));
app.post('/api/admin/fees/:id/status',adminOnly,(req,res)=>{const status=String(req.body.status||'');if(!['pending','approved','rejected'].includes(status))return res.status(400).json({message:'Invalid status'});q('UPDATE fee_payments SET status=?,reviewed_at=? WHERE id=?').run(status,now(),req.params.id);res.json({ok:true});});
app.get('/api/admin/notices',adminOnly,(req,res)=>res.json({notices:q('SELECT * FROM notices ORDER BY id DESC').all()}));
app.post('/api/admin/notices',adminOnly,(req,res)=>{const {title,message,enabled=true}=req.body;if(!title||!message)return res.status(400).json({message:'Title/message required'});const id=q('INSERT INTO notices(title,message,enabled,created_at) VALUES(?,?,?,?)').run(title,message,enabled?1:0,now()).lastInsertRowid;res.json({ok:true,id});});
app.post('/api/admin/notices/:id/toggle',adminOnly,(req,res)=>{q('UPDATE notices SET enabled=? WHERE id=?').run(req.body.enabled?1:0,req.params.id);res.json({ok:true});});

const siteDir=path.join(__dirname,'..','site');app.use(express.static(siteDir));app.get('*',(req,res)=>res.sendFile(path.join(siteDir,'index.html')));
app.listen(PORT,()=>console.log(`Masud JR API running on ${PORT}`));
