const API='https://masud-jr-official-online.onrender.com';let S=localStorage.getItem('mjrAdminSession')||'';const $=id=>document.getElementById(id);async function api(p,o={}){const h={'Content-Type':'application/json',...(o.headers||{})};if(S)h['x-admin-session']=S;const r=await fetch(API+p,{...o,headers:h});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'Error');return d}
async function login(){try{const d=await api('/api/admin/login',{method:'POST',body:JSON.stringify({username:$('user').value,password:$('pass').value})});S=d.session;localStorage.setItem('mjrAdminSession',S);openApp()}catch(e){$('msg').textContent=e.message}}
function openApp(){$('login').classList.add('hidden');$('app').classList.remove('hidden');loadAll()}async function loadAll(){await Promise.all([dashboard(),users(),tasks(),fees(),withdrawals(),notices()])}
async function dashboard(){const d=await api('/api/admin/dashboard');$('users').textContent=d.users;$('active').textContent=d.active;$('pending').textContent=d.pending;$('paid').textContent='৳'+d.paid}
async function users(){const d=await api('/api/admin/users');$('userTable').innerHTML='<table><tr><th>ID</th><th>Name</th><th>Balance</th><th>Status</th><th>Action</th></tr>'+d.users.map(u=>`<tr><td>${u.id}</td><td>${u.name}</td><td>৳${u.balance}</td><td>${u.blocked?'Blocked':'Active'}</td><td><button class="small" onclick="toggleUser(${u.id},${u.blocked?0:1})">${u.blocked?'Unblock':'Block'}</button> <button class="small" onclick="adjust(${u.id})">Balance</button></td></tr>`).join('')+'</table>'}
async function toggleUser(id,blocked){await api('/api/admin/users/'+id+'/block',{method:'POST',body:JSON.stringify({blocked})});users();dashboard()}async function adjust(id){const d=prompt('Balance adjustment (+/- amount)');if(d===null)return;await api('/api/admin/users/'+id+'/balance',{method:'POST',body:JSON.stringify({delta:Number(d)})});users();dashboard()}
async function tasks(){const d=await api('/api/admin/tasks');$('taskTable').innerHTML='<table><tr><th>Title</th><th>Type</th><th>Reward</th><th>Enabled</th><th>Action</th></tr>'+d.tasks.map(t=>`<tr><td>${t.title}</td><td>${t.type}</td><td>৳${t.reward}</td><td>${t.enabled?'Yes':'No'}</td><td><button class="small" onclick="toggleTask(${t.id},${t.enabled?0:1})">Toggle</button></td></tr>`).join('')+'</table>'}
$('taskForm').addEventListener('submit',async e=>{e.preventDefault();await api('/api/admin/tasks',{method:'POST',body:JSON.stringify({title:$('tTitle').value,type:$('tType').value,url:$('tUrl').value,reward:Number($('tReward').value),description:$('tDesc').value})});e.target.reset();tasks()});async function toggleTask(id,enabled){await api('/api/admin/tasks/'+id+'/toggle',{method:'POST',body:JSON.stringify({enabled})});tasks()}
async function fees(){const d=await api('/api/admin/fees');$('feeTable').innerHTML='<table><tr><th>User</th><th>TXID</th><th>Amount</th><th>Status</th><th>Action</th></tr>'+d.fees.map(f=>`<tr><td>${f.name}</td><td>${f.transaction_id}</td><td>৳${f.amount}</td><td>${f.status}</td><td><button class="small" onclick="feeStatus(${f.id},'approved')">Approve</button> <button class="small" onclick="feeStatus(${f.id},'rejected')">Reject</button></td></tr>`).join('')+'</table>'}async function feeStatus(id,status){await api('/api/admin/fees/'+id+'/status',{method:'POST',body:JSON.stringify({status})});fees()}
async function withdrawals(){const d=await api('/api/admin/withdrawals');$('withdrawTable').innerHTML='<table><tr><th>User</th><th>Method</th><th>Account</th><th>Amount</th><th>Status</th><th>Action</th></tr>'+d.withdrawals.map(w=>`<tr><td>${w.name}</td><td>${w.method}</td><td>${w.account_number}</td><td>৳${w.amount}</td><td>${w.status}</td><td><button class="small" onclick="wStatus(${w.id},'approved')">Approve</button> <button class="small" onclick="wStatus(${w.id},'paid')">Paid</button> <button class="small" onclick="wStatus(${w.id},'rejected')">Reject</button></td></tr>`).join('')+'</table>'}async function wStatus(id,status){await api('/api/admin/withdrawals/'+id+'/status',{method:'POST',body:JSON.stringify({status})});withdrawals();dashboard();users()}
async function notices(){const d=await api('/api/admin/notices');$('noticeTable').innerHTML='<table><tr><th>Title</th><th>Message</th><th>Enabled</th><th>Action</th></tr>'+d.notices.map(n=>`<tr><td>${n.title}</td><td>${n.message}</td><td>${n.enabled?'Yes':'No'}</td><td><button class="small" onclick="toggleNotice(${n.id},${n.enabled?0:1})">Toggle</button></td></tr>`).join('')+'</table>'}async function toggleNotice(id,enabled){await api('/api/admin/notices/'+id+'/toggle',{method:'POST',body:JSON.stringify({enabled})});notices()}
$('noticeForm').addEventListener('submit',async e=>{e.preventDefault();await api('/api/admin/notices',{method:'POST',body:JSON.stringify({title:$('nTitle').value,message:$('nMsg').value})});e.target.reset();notices()});async function logout(){try{await api('/api/admin/logout',{method:'POST'})}catch{}localStorage.removeItem('mjrAdminSession');S='';location.reload()}if(S)openApp();
